language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
script:
- ./build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gturnquist@pivotal.io
  password:
    secure: RQrH4HeZl1736GZ3c/C9+WfbFWrPCuxds8FXOGcJqCmBYNd33vQSuzUgUBxub0glX38ML2X6h3aE8imE0vG9N7/W4/gYomnTyM1U9PMlyE9i2JInOu+xw1JgnrXkBZAXcW8BsEd5NujWpYjOaJs/2br3lyurlXPv+vb1QofVpPQ=
  organization: spring.io
  space: Guides
  on:
    repo: gregturn/drone-aggregator
    branch: master
notifications:
  slack:
    secure: aN/QqcjMFa31VzcWaMoKGX/Ln5TWsB18fnIbNjS+IYUCgd3tUeiMEBxL/xqBoY73bNj2LFbXUhe4+GqErRfbPGGsqhPtSt+n/pq3ueBn3nQ9EYteRqzxd8tgDZ0SfUPwFJWfUjUHe6beXVJZUZrPYBAXuHYnSbZZnVFgv58ulUo=
