language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
- wget -O cf-linux-amd64.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.2&source=github-rel"
- chmod 755 ./cf
script:
- ./build
after_success:
  "cf auth $CF_USERNAME $CF_PASSWORD"
  "cf push -f manifest.yml"
  "cf push -f manifest-pcf.yml"
notifications:
  slack:
    secure: aN/QqcjMFa31VzcWaMoKGX/Ln5TWsB18fnIbNjS+IYUCgd3tUeiMEBxL/xqBoY73bNj2LFbXUhe4+GqErRfbPGGsqhPtSt+n/pq3ueBn3nQ9EYteRqzxd8tgDZ0SfUPwFJWfUjUHe6beXVJZUZrPYBAXuHYnSbZZnVFgv58ulUo=
