language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
script:
- ./build
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gturnquist@pivotal.io
  password:
    secure: SXK6lVPpU9wJVT27y9sxyhVH3vkt7701sJPMOUhc70jgbW9evEB1U96yqCqi4ytNvB1q0iG5mYZFKlzAnT52D2QuPlPEkgvBYjMWvzpCzXJ9hHg6v6vBk2pMwkl0GhF5Wt6evvrmDNvyLE5Ll/niY8MAWFRp1KpuxvCOnYVDGrA=
  organization: spring.io
  space: Guides
  on:
    repo: spring-guides/drone-aggregator
    branch: master
notifications:
  slack:
    secure: aN/QqcjMFa31VzcWaMoKGX/Ln5TWsB18fnIbNjS+IYUCgd3tUeiMEBxL/xqBoY73bNj2LFbXUhe4+GqErRfbPGGsqhPtSt+n/pq3ueBn3nQ9EYteRqzxd8tgDZ0SfUPwFJWfUjUHe6beXVJZUZrPYBAXuHYnSbZZnVFgv58ulUo=
