language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
script:
- ./build
deploy:
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pivotal.io
    username: gturnquist@pivotal.io
    organization: spring.io
    space: Guides
    on:
      repo: spring-guides/drone-aggregator
      branch: master
    password:
      secure: AmOPYpd8TtBKPYbkrkIhWcjcRbRtVeP8/kYHfEUIG7L2kqNE4PHxwnso5jFbQGbwWz/pjiHqkaGWrP1hnO9cR2cWoSVF0VlcSK8mWItqd4sNyju5gmrdKnySIkQMx7mQvaSwE6Odko6qicB71V7OpilLc3L0MI/zisWbJByYf1g=
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pivotal.io
    username: gturnquist@pivotal.io
    organization: pivotal
    space: pcf-architecture
    on:
      repo: spring-guides/drone-aggregator
      branch: master
    password:
      secure: AmOPYpd8TtBKPYbkrkIhWcjcRbRtVeP8/kYHfEUIG7L2kqNE4PHxwnso5jFbQGbwWz/pjiHqkaGWrP1hnO9cR2cWoSVF0VlcSK8mWItqd4sNyju5gmrdKnySIkQMx7mQvaSwE6Odko6qicB71V7OpilLc3L0MI/zisWbJByYf1g=
notifications:
  slack:
    secure: aN/QqcjMFa31VzcWaMoKGX/Ln5TWsB18fnIbNjS+IYUCgd3tUeiMEBxL/xqBoY73bNj2LFbXUhe4+GqErRfbPGGsqhPtSt+n/pq3ueBn3nQ9EYteRqzxd8tgDZ0SfUPwFJWfUjUHe6beXVJZUZrPYBAXuHYnSbZZnVFgv58ulUo=
