language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
- wget -O cf-linux-amd64.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.11.2&source=github-rel"
- tar xvfz cf-linux-amd64.tgz
- chmod 755 ./cf
script:
- ./build
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ]; then ./deploy ; fi
notifications:
  slack:
    secure: JFLrt+mLw8wmcuFv7IJQ3msgys9bYyFcThUDJ60OLEmK8F+MUXFBiEiBfN+zSHok1plxSghUZj1bSzAiQ530z0EUa66y2xo6FuBtcVCV+t4lNuhEc9lNaSb2IyQGDv3jlNJrX/nByiB/fT1iv01s4x6z54VjkR+R/iiS3Th1AJ8=
