language: groovy
jdk:
- oraclejdk8
sudo: required
before_install:
- gem install sass
- npm install -g bower
- wget http://repo.spring.io/release/org/springframework/boot/spring-boot-cli/1.2.3.RELEASE/spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- tar xvfz spring-boot-cli-1.2.3.RELEASE-bin.tar.gz
- export PATH=$PATH:spring-1.2.3.RELEASE/bin
- spring --version
script:
- ./build
deploy:
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pivotal.io
    username: gturnquist@pivotal.io
    organization: spring.io
    space: Guides
    on:
      repo: spring-guides/drone-aggregator
      branch: master
  - provider: cloudfoundry
    edge: true
    api: https://api.run.pivotal.io
    username: gturnquist@pivotal.io
    organization: pivotal
    space: pcf-architecture
    on:
      repo: spring-guides/drone-aggregator
      branch: master
  password:
    secure: ibgoXvJIfOWO8VQTXMveNn6Kai//6V8iQBQ1u13sJ07QSFQvLepUXfCSp+qEN6yL/3dZfZeAoccbGGEP/UsQb40+GyOXtmG/YSELqupc7kXfzV/zi91SXyfWCXvtO3cD+3GsI5FGLTzahVJTurWUETuy3KLN0nYeky5/uuivgN8=
notifications:
  slack:
    secure: aN/QqcjMFa31VzcWaMoKGX/Ln5TWsB18fnIbNjS+IYUCgd3tUeiMEBxL/xqBoY73bNj2LFbXUhe4+GqErRfbPGGsqhPtSt+n/pq3ueBn3nQ9EYteRqzxd8tgDZ0SfUPwFJWfUjUHe6beXVJZUZrPYBAXuHYnSbZZnVFgv58ulUo=
